# Generated by Django 3.2.3 on 2021-06-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_game_hero_playerhero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerhero',
            name='winrate',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
