# Generated by Django 3.2.3 on 2021-06-18 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_game_hero_playerhero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playerhero'),
        ),
    ]
