# Generated by Django 3.2.3 on 2021-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20210618_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(choices=[(1, 'Win'), (2, 'Loss'), (3, 'Invalid')], max_length=200, null=True),
        ),
    ]
